import turtle
a=turtle.Pen()
a.color('red')
a.circle(25)
b=turtle.Pen()
b.color('purple')
b.circle(25)
c=turtle.Pen()
c.color('purple')
c.circle(25)
c.color('blue')
d=turtle.Pen()
d.color('green')
d.circle(25)
turtle.exitonclick
