import turtle
a=turtle.Pen()
a.color('pink')
a.shape('circle')
b=turtle.Pen()
b.color('purple')
b.shape('circle')
a.forward(200)
b.forward(99999999)
b.left(70)
b.forward(70)
b.right(90)
b.forward(100)

turtle.exitonclick()